const ADD_TAB = 'ADD_TAB';
const EDIT_TAB = 'EDIT_TAB';
const REMOVE_TAB = 'REMOVE_TAB';
const PUSH_PROFESSION = 'PUSH_PROFESSION';
const EDIT_PROFESSION = 'EDIT_PROFESSION';
const DELETE_PROFESSION = 'DELETE_PROFESSION';

export {
    ADD_TAB,
    EDIT_TAB,
    REMOVE_TAB,
    PUSH_PROFESSION,
    EDIT_PROFESSION,
    DELETE_PROFESSION
}