const ADD_TAB = 'ADD_TAB';
const EDIT_TAB = 'EDIT_TAB';
const REMOVE_TAB = 'REMOVE_TAB';

const CREATE_PROFESSION = 'CREATE_PROFESSION';
const EDIT_PROFESSION = 'EDIT_PROFESSION';
const DELETE_PROFESSION = 'DELETE_PROFESSION';
const GET_ALL_PROFESSIONS = 'GET_ALL_PROFESSIONS';
const SET_ROW_DATA_PROFESSION = 'GET_ALL_PROFESSIONS';

const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
const SET_ROW_DATA_DEPARTMENT = 'SET_ROW_DATA_DEPARTMENT';

const CREATE_PERSON = 'CREATE_PERSON';
const EDIT_PERSON = 'EDIT_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';
const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE';
const SET_ROW_DATA_PERSON = 'SET_ROW_DATA_PERSON';

const CREATE_TASK = 'CREATE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const DELETE_TASK = 'DELETE_TASK';
const GET_ALL_TASKS = 'GET_ALL_TASKS';
const SET_ROW_DATA_TASK = 'SET_ROW_DATA_TASK';

// Характеристики оборудования
const CREATE_EQUIPMENT_PROPERTY = 'CREATE_EQUIPMENT_PROPERTY';
const EDIT_EQUIPMENT_PROPERTY = 'EDIT_EQUIPMENT_PROPERTY';
const DELETE_EQUIPMENT_PROPERTY = 'DELETE_EQUIPMENT_PROPERTY';
const GET_ALL_EQUIPMENT_PROPERTIES = 'GET_ALL_EQUIPMENT_PROPERTIES';
const SET_ROW_DATA_EQUIPMENT_PROPERTY = 'SET_ROW_DATA_EQUIPMENT_PROPERTY';

// Установка активной вкладки
const SET_ACTIVE_KEY = 'SET_ACTIVE_KEY';
const SET_PREV_ACTIVE_TAB = 'SET_PREV_ACTIVE_TAB';

const SET_LOADING_SKELETON = 'SET_LOADING_SKELETON';

export {
    ADD_TAB,
    EDIT_TAB,
    REMOVE_TAB,

    CREATE_PROFESSION,
    EDIT_PROFESSION,
    DELETE_PROFESSION,
    GET_ALL_PROFESSIONS,
    SET_ROW_DATA_PROFESSION,

    CREATE_DEPARTMENT,
    EDIT_DEPARTMENT,
    DELETE_DEPARTMENT,
    GET_ALL_DEPARTMENTS,
    SET_ROW_DATA_DEPARTMENT,

    CREATE_PERSON,
    EDIT_PERSON,
    DELETE_PERSON,
    GET_ALL_PEOPLE,
    SET_ROW_DATA_PERSON,

    CREATE_TASK,
    EDIT_TASK,
    DELETE_TASK,
    GET_ALL_TASKS,
    SET_ROW_DATA_TASK,

    CREATE_EQUIPMENT_PROPERTY,
    EDIT_EQUIPMENT_PROPERTY,
    DELETE_EQUIPMENT_PROPERTY,
    GET_ALL_EQUIPMENT_PROPERTIES,
    SET_ROW_DATA_EQUIPMENT_PROPERTY,

    SET_ACTIVE_KEY,
    SET_PREV_ACTIVE_TAB,

    SET_LOADING_SKELETON
}