const ADD_TAB = 'ADD_TAB';
const EDIT_TAB = 'EDIT_TAB';
const REMOVE_TAB = 'REMOVE_TAB';

const GET_ALL_PROFESSIONS = 'GET_ALL_PROFESSIONS';
const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE';
const GET_ALL_TASKS = 'GET_ALL_TASKS';

const CREATE_PROFESSION = 'CREATE_PROFESSION';
const EDIT_PROFESSION = 'EDIT_PROFESSION';
const DELETE_PROFESSION = 'DELETE_PROFESSION';

const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

const CREATE_PERSON = 'CREATE_PERSON';
const EDIT_PERSON = 'EDIT_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';

const CREATE_TASK = 'CREATE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const DELETE_TASK = 'DELETE_TASK';

const SET_PREV_ACTIVE_TAB = 'SET_PREV_ACTIVE_TAB';

const SET_LOADING_SKELETON = 'SET_LOADING_SKELETON';

// Для теста==========================================
const TEST_DATA = 'TEST_DATA';
// ===================================================

export {
    ADD_TAB,
    EDIT_TAB,
    REMOVE_TAB,
    GET_ALL_PROFESSIONS,
    GET_ALL_DEPARTMENTS,
    GET_ALL_PEOPLE,
    GET_ALL_TASKS,
    CREATE_PROFESSION,
    EDIT_PROFESSION,
    DELETE_PROFESSION,
    CREATE_DEPARTMENT,
    EDIT_DEPARTMENT,
    DELETE_DEPARTMENT,
    CREATE_PERSON,
    EDIT_PERSON,
    DELETE_PERSON,
    CREATE_TASK,
    EDIT_TASK,
    DELETE_TASK,
    SET_PREV_ACTIVE_TAB,
    SET_LOADING_SKELETON,
    TEST_DATA
}