const ADD_TAB = 'ADD_TAB';
const EDIT_TAB = 'EDIT_TAB';
const REMOVE_TAB = 'REMOVE_TAB';

const PUSH_PROFESSION = 'PUSH_PROFESSION';
const EDIT_PROFESSION = 'EDIT_PROFESSION';
const DELETE_PROFESSION = 'DELETE_PROFESSION';

const PUSH_DEPARTMENT = 'PUSH_DEPARTMENT';
const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

const PUSH_PERSON = 'PUSH_PERSON';
const EDIT_PERSON = 'EDIT_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';

export {
    ADD_TAB,
    EDIT_TAB,
    REMOVE_TAB,
    PUSH_PROFESSION,
    EDIT_PROFESSION,
    DELETE_PROFESSION,
    PUSH_DEPARTMENT,
    EDIT_DEPARTMENT,
    DELETE_DEPARTMENT,
    PUSH_PERSON,
    EDIT_PERSON,
    DELETE_PERSON
}