const ADD_TAB = 'ADD_TAB';
const EDIT_TAB = 'EDIT_TAB';
const REMOVE_TAB = 'REMOVE_TAB';

const GET_ALL_PROFESSIONS = 'GET_ALL_PROFESSIONS';
const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE';

const CREATE_PROFESSION = 'CREATE_PROFESSION';
const EDIT_PROFESSION = 'EDIT_PROFESSION';
const DELETE_PROFESSION = 'DELETE_PROFESSION';

const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

const CREATE_PERSON = 'CREATE_PERSON';
const EDIT_PERSON = 'EDIT_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';

const SET_PREV_ACTIVE_TAB = 'SET_PREV_ACTIVE_TAB';

export {
    ADD_TAB,
    EDIT_TAB,
    REMOVE_TAB,
    GET_ALL_PROFESSIONS,
    GET_ALL_DEPARTMENTS,
    GET_ALL_PEOPLE,
    CREATE_PROFESSION,
    EDIT_PROFESSION,
    DELETE_PROFESSION,
    CREATE_DEPARTMENT,
    EDIT_DEPARTMENT,
    DELETE_DEPARTMENT,
    CREATE_PERSON,
    EDIT_PERSON,
    DELETE_PERSON,
    SET_PREV_ACTIVE_TAB
}